package com.medbot.app.data.rag

import com.medbot.app.domain.model.DocChunk

class DocumentChunker(
    private val chunkSizeWords: Int = 120, // ~512 tokens
    private val overlapWords: Int = 20
) {

    fun chunkDocument(docId: String, parsedDoc: ParsedDocument, embedder: LocalEmbedder): List<DocChunk> =
        chunkDocumentInternal(docId, parsedDoc) { embedder.embed(it) }

    /**
     * Reuses vectors generated by the same verified embedding model. The list
     * is consumed only for non-empty chunks; a count mismatch fails closed so
     * a stale or truncated precomputed index can never be promoted to Room.
     */
    fun chunkDocumentWithEmbeddings(
        docId: String,
        parsedDoc: ParsedDocument,
        embeddings: List<FloatArray>
    ): List<DocChunk> {
        var embeddingIndex = 0
        val chunks = chunkDocumentInternal(docId, parsedDoc) {
            embeddings.getOrNull(embeddingIndex++)
                ?: throw RagProcessingException(
                    RagFailureCode.EMBEDDER_UNAVAILABLE,
                    "Precomputed embedding count is smaller than the document chunk count"
                )
        }
        if (embeddingIndex != embeddings.size) {
            throw RagProcessingException(
                RagFailureCode.EMBEDDER_UNAVAILABLE,
                "Precomputed embedding count is larger than the document chunk count"
            )
        }
        return chunks
    }

    private fun chunkDocumentInternal(
        docId: String,
        parsedDoc: ParsedDocument,
        embed: (String) -> FloatArray
    ): List<DocChunk> {
        val chunks = mutableListOf<DocChunk>()
        var chunkIndex = 0

        for (page in parsedDoc.pages) {
            val words = page.text.split(Regex("\\s+")).filter { it.isNotBlank() }
            if (words.isEmpty()) continue

            var startIndex = 0
            while (startIndex < words.size) {
                val endIndex = (startIndex + chunkSizeWords).coerceAtMost(words.size)
                val chunkWords = words.subList(startIndex, endIndex)
                val chunkText = chunkWords.joinToString(" ")

                val vector = embed(chunkText)

                chunks.add(
                    DocChunk(
                        id = "${docId}:${chunkIndex}",
                        docId = docId,
                        chunkIndex = chunkIndex++,
                        textContent = chunkText,
                        pageNumber = page.pageNumber,
                        sectionTitle = page.sectionTitle.ifBlank {
                            if (page.pageNumber > 0) "Halaman ${page.pageNumber}" else "Bagian tanpa nomor halaman"
                        },
                        embedding = vector,
                        recordId = page.recordId,
                        sourceRole = page.sourceRole,
                        sourceUrl = page.sourceUrl,
                        sourceSha256 = page.sourceSha256,
                        revision = page.revision,
                        evidenceKind = page.evidenceKind,
                        citationId = "${page.recordId.ifBlank { docId }}:${chunkIndex - 1}"
                    )
                )

                if (endIndex == words.size) break
                startIndex += (chunkSizeWords - overlapWords).coerceAtLeast(1)
            }
        }
        return chunks
    }
}
