package com.medbot.app.data.rag

import com.medbot.app.data.local.dao.RagDao
import com.medbot.app.data.local.entities.DocChunkEntity
import com.medbot.app.data.local.entities.RagDocumentEntity
import com.medbot.app.domain.model.Citation
import com.medbot.app.domain.model.ClinicalEvidenceKind
import com.medbot.app.domain.model.ClinicalEvidenceSourceRole
import com.medbot.app.domain.model.DocChunk
import com.medbot.app.domain.model.RagDocument
import com.medbot.app.domain.model.SearchResult
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext
import java.io.InputStream
import java.util.UUID

/** Coordinates real local parsing, embedding, persistence, and retrieval. */
class RagOrchestrator(
    private val ragDao: RagDao,
    private val parser: DocumentParser = DocumentParser(),
    private val chunker: DocumentChunker = DocumentChunker(),
    private val embedder: LocalEmbedder = LocalEmbedder(),
    private val vectorEngine: VectorSearchEngine = VectorSearchEngine()
) {
    fun getDocumentsFlow(): Flow<List<RagDocument>> = ragDao.getDocuments().map { list ->
        list.map { it.toDomain() }
    }

    suspend fun ingestDocument(
        fileName: String,
        fileUri: String,
        mimeType: String,
        inputStream: InputStream,
        documentId: String = UUID.randomUUID().toString()
    ): Result<RagDocument> = ingestDocumentInternal(
        fileName = fileName,
        fileUri = fileUri,
        mimeType = mimeType,
        inputStream = inputStream,
        documentId = documentId,
        precomputedEmbeddings = null
    )

    /**
     * Imports a document whose vectors were generated by the pinned local
     * embedder. This keeps first-run corpus setup fast while the query side
     * still uses the same verified model for new questions.
     */
    suspend fun ingestDocumentWithPrecomputedEmbeddings(
        fileName: String,
        fileUri: String,
        mimeType: String,
        inputStream: InputStream,
        embeddings: List<FloatArray>,
        documentId: String = UUID.randomUUID().toString(),
        previousDocumentId: String? = null
    ): Result<RagDocument> = ingestDocumentInternal(
        fileName = fileName,
        fileUri = fileUri,
        mimeType = mimeType,
        inputStream = inputStream,
        documentId = documentId,
        precomputedEmbeddings = embeddings,
        previousDocumentId = previousDocumentId
    )

    private suspend fun ingestDocumentInternal(
        fileName: String,
        fileUri: String,
        mimeType: String,
        inputStream: InputStream,
        documentId: String,
        precomputedEmbeddings: List<FloatArray>?,
        previousDocumentId: String? = null
    ): Result<RagDocument> = withContext(Dispatchers.IO) {
        try {
            val parsed = parser.parse(inputStream, fileName, mimeType)
            val chunks = precomputedEmbeddings?.let { embeddings ->
                chunker.chunkDocumentWithEmbeddings(documentId, parsed, embeddings)
            } ?: chunker.chunkDocument(documentId, parsed, embedder)
            if (chunks.isEmpty()) {
                throw RagProcessingException(RagFailureCode.INVALID_DOCUMENT, "Document produced no chunks")
            }
            // JSON metadata is retained by the parser for provenance, but it
            // is not a trust boundary. Only the exact release-owned asset may
            // claim an authoritative role or medication evidence kind.
            val releaseOwned = fileUri == BankBookCorpusManifest.ASSET_URI &&
                parsed.fileName == BankBookCorpusManifest.ASSET_FILE_NAME &&
                parsed.byteSize == BankBookCorpusManifest.BYTE_SIZE &&
                parsed.sha256.equals(BankBookCorpusManifest.SHA256, ignoreCase = true)
            val declaredRole = parsed.pages.firstOrNull { it.sourceRole.isNotBlank() }
                ?.sourceRole
                ?.let(ClinicalEvidenceSourceRole::fromWireValue)
                ?: ClinicalEvidenceSourceRole.UNKNOWN
            val sourceRole = if (releaseOwned) {
                declaredRole
                    .takeIf { it != ClinicalEvidenceSourceRole.UNKNOWN }
                    ?.wireValue
                    ?: ClinicalEvidenceSourceRole.NATIONAL_CLINICAL_GUIDELINE.wireValue
            } else {
                ClinicalEvidenceSourceRole.USER_PROVIDED.wireValue
            }
            val declaredKind = parsed.pages.firstOrNull { it.evidenceKind.isNotBlank() }
                ?.evidenceKind
                ?.let(ClinicalEvidenceKind::fromWireValue)
                ?: ClinicalEvidenceKind.UNKNOWN
            val evidenceKind = when {
                releaseOwned && declaredKind != ClinicalEvidenceKind.UNKNOWN -> declaredKind.wireValue
                releaseOwned -> ClinicalEvidenceKind.GUIDELINE.wireValue
                // User-owned sources may explicitly identify themselves as a
                // monograph, guideline, interaction, or protocol. Their role
                // remains USER_PROVIDED, so the citation cannot masquerade as
                // an official source, but the typed evidence can still be
                // audited against the actual imported bytes.
                declaredKind != ClinicalEvidenceKind.UNKNOWN -> declaredKind.wireValue
                else -> ClinicalEvidenceKind.USER_PROVIDED_DOCUMENT.wireValue
            }
            val document = RagDocumentEntity(
                id = documentId,
                fileName = parsed.fileName,
                fileUri = fileUri,
                mimeType = mimeType,
                fileSize = parsed.byteSize,
                pageCount = parsed.totalPageCount,
                chunkCount = chunks.size,
                sha256 = parsed.sha256,
                embeddingModel = embedder.manifest.source,
                embeddingModelSha256 = embedder.manifest.modelSha256,
                embeddingVersion = embedder.manifest.version,
                sourceRole = sourceRole,
                sourceUrl = if (releaseOwned) {
                    parsed.pages.firstOrNull { it.sourceUrl.isNotBlank() }?.sourceUrl.orEmpty()
                } else {
                    ""
                },
                revision = if (releaseOwned) {
                    parsed.pages.firstOrNull { it.revision.isNotBlank() }?.revision.orEmpty()
                } else {
                    ""
                },
                recordId = parsed.pages.firstOrNull { it.recordId.isNotBlank() }?.recordId.orEmpty(),
                indexedAt = System.currentTimeMillis()
            )
            val entities = chunks.map { chunk ->
                DocChunkEntity(
                    id = chunk.id,
                    docId = chunk.docId,
                    chunkIndex = chunk.chunkIndex,
                    textContent = chunk.textContent,
                    pageNumber = chunk.pageNumber,
                    sectionTitle = chunk.sectionTitle,
                    embeddingCsv = embedder.vectorToCsv(chunk.embedding),
                    recordId = chunk.recordId,
                    sourceRole = if (releaseOwned) chunk.sourceRole.ifBlank { sourceRole } else sourceRole,
                    sourceUrl = if (releaseOwned) chunk.sourceUrl else "",
                    sourceSha256 = parsed.sha256,
                    revision = if (releaseOwned) chunk.revision else "",
                    // Preserve per-record material kind from JSONL. For a
                    // user-selected corpus the source role is intentionally
                    // downgraded to USER_PROVIDED, but an explicitly declared
                    // monograph/guideline/protocol must not be flattened to
                    // the first record's kind.
                    evidenceKind = chunk.evidenceKind.ifBlank { evidenceKind },
                    citationId = chunk.citationId
                )
            }
            ragDao.replaceDocumentWithChunks(previousDocumentId, document, entities)
            Result.success(document.toDomain())
        } catch (error: CancellationException) {
            throw error
        } catch (t: Throwable) {
            Result.failure(t)
        }
    }

    /** Returns a previously indexed source without reading or re-embedding it. */
    suspend fun getDocumentByFileUri(fileUri: String): RagDocument? = withContext(Dispatchers.IO) {
        ragDao.getDocumentByFileUri(fileUri)?.toDomain()
    }

    suspend fun searchSimilar(query: String, topK: Int = 4): List<SearchResult> = withContext(Dispatchers.IO) {
        val queryVector = embedder.embed(query)
        val documents = ragDao.getDocuments().first()
            .filter(::hasCurrentEmbedding)
            .associateBy { it.id }
        val chunks = ragDao.getAllChunks().mapNotNull { entity ->
            val document = documents[entity.docId] ?: return@mapNotNull null
            val chunk = DocChunk(
                id = entity.id,
                docId = entity.docId,
                chunkIndex = entity.chunkIndex,
                textContent = entity.textContent,
                pageNumber = entity.pageNumber,
                sectionTitle = entity.sectionTitle,
                embedding = embedder.csvToVector(entity.embeddingCsv),
                recordId = entity.recordId,
                sourceRole = entity.sourceRole,
                sourceUrl = entity.sourceUrl,
                sourceSha256 = entity.sourceSha256.ifBlank { document.sha256 },
                revision = entity.revision,
                evidenceKind = entity.evidenceKind,
                citationId = entity.citationId
            )
            // JSONL corpus records carry the clinical topic and source book in
            // sectionTitle (for example, "Diare • Kapita Selekta..."). Use
            // that verified metadata for ranking so a generic symptom mention
            // cannot outrank the exact clinical topic. User-imported files do
            // not have this compound metadata, so their file name remains the
            // citation title.
            val retrievalTitle = entity.sectionTitle
                .takeIf { it.contains(" • ") }
                ?.trim()
                ?.takeIf { it.isNotBlank() }
                ?: document.fileName
            chunk to retrievalTitle
        }
        vectorEngine.searchTopK(queryVector, chunks, topK = topK, queryText = query).map { result ->
            val document = documents[result.chunk.docId]
            result.copy(
                documentUri = document?.fileUri.orEmpty(),
                sourceRole = result.chunk.sourceRole,
                sourceUrl = result.chunk.sourceUrl,
                sourceSha256 = result.chunk.sourceSha256.ifBlank { document?.sha256.orEmpty() },
                recordId = result.chunk.recordId,
                revision = result.chunk.revision,
                evidenceKind = result.chunk.evidenceKind,
                citationId = result.chunk.citationId
            )
        }
    }

    suspend fun deleteDocument(docId: String) = withContext(Dispatchers.IO) { ragDao.deleteDocument(docId) }

    /**
     * Counts only chunks whose document was embedded by the currently bundled
     * local embedder. Legacy rows with empty or stale provenance must not make
     * the chat believe that a usable index exists.
     */
    suspend fun getChunkCount(): Int = withContext(Dispatchers.IO) {
        val eligibleDocumentIds = ragDao.getDocuments().first()
            .filter(::hasCurrentEmbedding)
            .mapTo(mutableSetOf()) { it.id }
        if (eligibleDocumentIds.isEmpty()) return@withContext 0
        ragDao.getAllChunks().count { it.docId in eligibleDocumentIds }
    }

    /** Checks whether a persisted domain document belongs to the current vector space. */
    fun hasCurrentEmbedding(document: RagDocument): Boolean =
        document.embeddingModel == embedder.manifest.source &&
            document.embeddingModelSha256.equals(embedder.manifest.modelSha256, ignoreCase = true) &&
            document.embeddingVersion == embedder.manifest.version

    fun buildContextAndCitations(searchResults: List<SearchResult>): Pair<String, List<Citation>> {
        if (searchResults.isEmpty()) return "" to emptyList()
        val context = searchResults.mapIndexed { index, result ->
            val location = if (result.chunk.pageNumber > 0) {
                "page ${result.chunk.pageNumber}"
            } else {
                "non-paginated section"
            }
            "[Source ${index + 1} - ${result.documentTitle}, $location]:\n${result.chunk.textContent}"
        }.joinToString("\n\n")
        val citations = searchResults.map { result ->
            Citation(
                citationId = result.citationId.ifBlank { "local:${result.chunk.docId}:${result.chunk.chunkIndex}" },
                documentTitle = result.documentTitle,
                pageNumber = result.chunk.pageNumber,
                snippet = result.chunk.textContent.take(150),
                sectionTitle = result.chunk.sectionTitle,
                sourceUri = result.documentUri,
                sourceUrl = result.sourceUrl,
                sourceName = result.documentTitle,
                sourceRole = result.sourceRole,
                sourceSha256 = result.sourceSha256,
                recordId = result.recordId,
                revision = result.revision
            )
        }
        return context to citations
    }

    private fun RagDocumentEntity.toDomain() = RagDocument(
        id = id,
        fileName = fileName,
        fileUri = fileUri,
        mimeType = mimeType,
        fileSize = fileSize,
        pageCount = pageCount,
        chunkCount = chunkCount,
        sha256 = sha256,
        embeddingModel = embeddingModel,
        embeddingModelSha256 = embeddingModelSha256,
        embeddingVersion = embeddingVersion,
        sourceRole = sourceRole,
        sourceUrl = sourceUrl,
        revision = revision,
        recordId = recordId,
        indexedAt = indexedAt
    )

    private fun hasCurrentEmbedding(document: RagDocumentEntity): Boolean =
        document.embeddingModel == embedder.manifest.source &&
            document.embeddingModelSha256.equals(embedder.manifest.modelSha256, ignoreCase = true) &&
            document.embeddingVersion == embedder.manifest.version
}
